name: client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  fpdart: ^2.0.0-dev.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  shared_preferences: ^2.5.3

dev_dependencies:
  dev: ^1.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
